services:
    db:
        image: postgres:latest
        container_name: postgres_db
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app-network

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - app-network

    api:
        image: mcr.microsoft.com/dotnet/sdk:8.0
        container_name: api
        working_dir: /app/back
        volumes:
            - ./back:/app/back
            - ~/.nuget/packages:/root/.nuget/packages
        ports:
            - "5251:5251"
        command: dotnet watch --project ./Application run --urls=http://0.0.0.0:5251
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
            Redis__Configuration: "redis:6379"
        depends_on:
            - db
            - redis
        networks:
            - app-network

volumes:
    db_data:

networks:
    app-network:
        driver: bridge